Models/CesarViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace VigenereWeb.Models
{
    public class CesarViewModel
    {
        [Required]
        public string Mensaje { get; set; }

        [Required]
        public int Clave { get; set; }
    }

}

Models/ErrorViewModel.cs
using System;

namespace VigenereWeb.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/VigenereViewModes.cs
using System.ComponentModel.DataAnnotations;

namespace VigenereWeb.Models
{
    public class VigenereViewModel
    {
        [Required]
        [MinLength(1)]
        public string Mensaje { get; set; }

        [Required]
        [MinLength(1)]
        public string Clave { get; set; }
    }

}

Controllers/CesarController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VigenereWeb.Models;
using VigenereWeb.Services;

namespace CesarWeb.Controllers
{
    public class CesarController : Controller
    {
        private ISeguridadService<string> _seguridadService;

        public CesarController(ISeguridadService<string> VigenereSeguridadService)
        {
            _seguridadService = VigenereSeguridadService;
        }

        
        [HttpPost]
        public IActionResult Encriptar(CesarViewModel mensajeAEncriptar)
        {
            mensajeAEncriptar.Mensaje = _seguridadService.Encriptar(mensajeAEncriptar.Mensaje, mensajeAEncriptar.Clave);
            return View(mensajeAEncriptar);
        }

        [HttpPost]
        public IActionResult Desencriptar(CesarViewModel mensajeADesencriptar)
        {
            mensajeADesencriptar.Mensaje = _seguridadService.DesEncriptar(mensajeADesencriptar.Mensaje, mensajeADesencriptar.Clave);
            return View(mensajeADesencriptar);
        }


    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VigenereWeb.Models;

namespace VigenereWeb.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Encriptar()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Desencriptar()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }


    }
}

Controllers/VigenereController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using VigenereWeb.Models;
using VigenereWeb.Services;

namespace CesarWeb.Controllers
{
    public class VigenereController : Controller
    {
        private ISeguridadService<string> _seguridadService;

        public VigenereController(ISeguridadService<string> seguridadService)
        {
            _seguridadService = seguridadService;
        }

        
        [HttpPost]
        public IActionResult Encriptar(VigenereViewModel mensajeAEncriptar)
        {
            mensajeAEncriptar.Mensaje = _seguridadService.Encriptar(mensajeAEncriptar.Mensaje, mensajeAEncriptar.Clave);
            return View(mensajeAEncriptar);
        }

        [HttpPost]
        public IActionResult Desencriptar(VigenereViewModel mensajeADesencriptar)
        {
            mensajeADesencriptar.Mensaje = _seguridadService.DesEncriptar(mensajeADesencriptar.Mensaje, mensajeADesencriptar.Clave);
            return View(mensajeADesencriptar);
        }


    }
}

Views/Cesar/Desencriptar.cshtml
@model CesarViewModel

<br/>
<div class="form-group">
  <label for="mensaje">Mensaje Desencriptado:</label>
  <textarea class="form-control" rows="5" id="mensaje">@Model.Mensaje</textarea>
</div>

Views/Cesar/Encriptar.cshtml
@model CesarViewModel

<br/>

<div class="form-group">
  <label for="mensaje">Mensaje Encriptado:</label>
  <textarea class="form-control" rows="5" id="mensaje">@Model.Mensaje</textarea>
</div>

Views/Home/Desencriptar.cshtml
<form asp-controller="Vigenere" asp-action="Desencriptar" method="POST">
    <div class="form-group">
    <br/>
    <div class="form-group">
    <label for="mensaje">Mensaje a Desencriptar:</label>
    <textarea class="form-control" rows="5" id="mensaje" name="mensaje" placeholder="Mensaje"></textarea>
    </div>
    <br/>
    <label for="clave">Clave: </label>
    <input type="text" class="form-control" name="clave">
    <br/>
    <button type="submit" class="btn btn-primary">Desencriptar</button>
    </div>
</form>

Views/Home/Encriptar.cshtml
<form asp-controller="Vigenere" asp-action="Encriptar" method="POST">
    <div class="form-group">
    <br/>
    <div class="form-group">
    <label for="mensaje">Mensaje a Encriptar:</label>
    <textarea class="form-control" rows="5" id="mensaje" name="mensaje" placeholder="Mensaje"></textarea>
    </div>
    <br/>
    <label for="clave">Clave: </label>
    <input type="text" class="form-control" name="clave">
    <br/>
    <button type="submit" class="btn btn-primary">Encriptar</button>
    </div>
</form>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VigenereWeb</title>


        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />


</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">VigenereWeb</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Encriptar">Encriptar</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Desencriptar">Desencriptar</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - CesarWeb</p>
        </footer>
    </div>


        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>

 

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Vigenere/Desencriptar.cshtml
@model VigenereViewModel

<br/>
<div class="form-group">
  <label for="mensaje">Mensaje Desencriptado:</label>
  <textarea class="form-control" rows="5" id="mensaje">@Model.Mensaje</textarea>
</div>

Views/Vigenere/Encriptar.cshtml
@model VigenereViewModel

<br/>

<div class="form-group">
  <label for="mensaje">Mensaje Encriptado:</label>
  <textarea class="form-control" rows="5" id="mensaje">@Model.Mensaje</textarea>
</div>